drop table if exists items cascade;

create table items(
    id bigint generated by default as identity primary key,
    stock_number varchar(6) not null unique,
    name varchar(255) not null,
    description varchar(4096),
    price bigint check (price>0),
    in_stock boolean
);

